name: pages

on:
  push:
    branches:
      - master
      - beta

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: UseNode
        uses: actions/setup-node@v3
        with:
          node-version: 16.18.0

      - name: Build
        run: |
          yarn install
          yarn run build:docs

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
          branch: gh-pages
          folder: 'docs/.vuepress/dist'
